package main

import "github.com/HiteshRepo/learninggist/DSAlgo/StriverQuestions/array"

func main() {
	// runTestsSortColors()
	// runTestsNextPermutation()
	// runTestsMaxProfit()
	// runTestsForRotateMatrix()
	// runTestsForMergeIntervals()
	// runTestsForMergeSortedArrays()
	// runTestsFindDuplicates()
	// array.RunTestsForSearchMatrixLinear()
	// array.RunTestsForSearchMatrixRowBinarySearch()
	// array.RunTestsForSearchMatrixRowFromLastTraverse()
	// array.RunTestsForSearchMatrixConsideringWholeMatrixAsSingleArray()
	// array.RunTestsForMyPowBruteForce()
	// array.RunTestsForMyPow_O_N()
	// array.RunTestsForMajorityElementGt2UsingFreqMap()
	// array.RunTestsForMajorityElementGt2UsingMooresVoting()
	// array.RunTestsForMajorityElementGt3()
	// array.RunTestsForUniquePaths()
	// array.RunTestsForUniquePathsDP()
	// array.RunTestsForReversePairsBruteForce()
	// array.RunTestsForReversePairsMergeSort()
	// array.RunTestCasesForTwoSumBruteForce()
	// array.RunTestCasesForTwoSum()
	// array.RunTestsFor4SumBruteForce()
	// array.RunTestsFor4SumOptimal()
	// array.RunTestsForLongestConsecutiveNaive()
	// array.RunTestsForLongestConsecutiveOptimized()
	// array.RunTestsForLargestSubArrWithSumZero()
	// log.Println(utils.GenerateSubArrayUsingKadanesN3([]int{2,3,4}))
	// log.Println(utils.GenerateSubArrayUsingKadanesN2([]int{2,3,4}))
	// log.Println(utils.IntCalculateXOR(6, 2))
	// array.RunTestsForFindSubArrForGivenXor()
	// array.RunTestsForFindSubArrForGivenXorOptimized()
	// array.RunTestsForLengthOfLongestSubstring()
	// array.RunTestsForLengthOfLongestSubstringOptimized()
	// array.RunTestsSetMatrixZeroesOptimized()
	// array.RunTestsPascalTriangle()
	// array.RunTestsPascalTriangleNumberAtRowColumn()
	// array.RunTestsPascalTriangleNthRow()
	// array.RunTestsNextPermutation()
	array.RunTestsSortColors()
}
